/**
 * Shared public API surface for all published entry points.
 */

export type {
    BooleanParams,
    BlendFaceResult,
    BlendOperationResult,
    BoundingBox,
    BoxParams,
    ChamferEdgeSpec,
    ChamferFeatureParams,
    ChamferParams,
    ChamferSpec,
    CreateCheckpointParams,
    CylinderParams,
    DisposeParams,
    EdgeCurveResult,
    EdgeEvaluationParams,
    EdgeEvaluationResult,
    EdgeRef,
    EdgeSample,
    EdgeSampleResult,
    EntityRevisionMapping,
    EntityRevisionMapResult,
    ExportStepParams,
    ExtrudeCutProfileFeatureParams,
    ExtrudeParams,
    ExtrudeProfileExtent,
    ExtrudeProfileFeatureParams,
    ExtrudeProfileSpec,
    ExtrudeSurfaceTarget,
    FaceEvaluationParams,
    FaceEvaluationResult,
    FaceRef,
    FeatureEdgeChain,
    FilletEdgeSpec,
    FilletFeatureParams,
    FilletParams,
    FilletRadiusLaw,
    FilletSpec,
    ImportStepParams,
    KernelCapabilities,
    HydrateCheckpointParams,
    LoftFeatureParams,
    LoftSection,
    MapEntitiesAcrossRevisionsParams,
    Profile,
    ProfileSegment,
    ProfileSegmentArc,
    ProfileSegmentBezier,
    ProfileSegmentBspline,
    ProfileSegmentCircle,
    ProfileSegmentLine,
    OperationSchema,
    RadiusStation,
    ReleaseRevisionParams,
    ResolveStableEntityParams,
    RetainRevisionParams,
    RevolveCutProfileFeatureParams,
    RevolveParams,
    RevolveProfileExtent,
    RevolveProfileFeatureParams,
    RevolveProfileSpec,
    RevolveSlidingEdgeSpec,
    RevolveSurfaceTarget,
    RevisionCheckpoint,
    RevisionIdentityStatus,
    RevisionInfo,
    ShapeHandle,
    SphereParams,
    StableEntityResolution,
    SpatialCurveSegment,
    SpatialCurveSegmentArc,
    SpatialCurveSegmentBezier,
    SpatialCurveSegmentBspline,
    SpatialCurveSegmentCircle,
    SpatialCurveSegmentLine,
    SpatialWire,
    SweepProfileFeatureParams,
    SweepProfileSpec,
    SweepTrihedronMode,
    TessellateParams,
    TessellationResult,
    TopologyDeletedEntity,
    TopologyEdge,
    TopologyEntityStatus,
    TopologyFace,
    TopologyResult,
    TopologyVertex,
} from './types';

export { KernelError } from './errors';
export type { KernelErrorCode } from './errors';
export { OcctKernel } from './kernel';
export type { NativeKernel, WasmModule } from './kernel';